### ISSUE TITLE
Arquero data manipulation in DE3-table-display.html

### ISSUE THREAD

**Issue by cgettings** [mmontesanonyc/vega-lite-library#3]
First, Arquero is loading and displaying that long file - I'd like to get it wide so that we're displaying Measures in separate columns, instead of in one Value column. 

Secondly, I started out on a GeoLookup file: https://github.com/mmontesanonyc/vega-lite-library/blob/main/GeoLookup.csv. We'll want to use Arquero to join this to whatever data file so that we can pipe in Geo Names into the table. 

I think this can all happen inside the .then() statement that runs when Arq loads the data file.

**Comment by cgettings** [comment]
@mmontesanonyc If you can assign to me, I can track it on my dashboard.

**Comment by mmontesanonyc** [comment]
Good idea. I've done that here, but how about this instead - move the necessary files into [this development repo](https://github.com/nycehs/Portal-Prototype-Working-Files) (maybe under Data Explorer Files?), and replicate the issue there. Made sense to keep this in a personal repo while I was just experimenting, but once we get to collective problem-solving/development, let's move into one of our shared spaces.

**Comment by mmontesanonyc** [comment]
Moved to org repo here: https://github.com/nycehs/Portal-Prototype-Working-Files/issues/2
